// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_bots': 'enable',
    'aws_bots_config': [{"name":"ListIngredientsBot","alias":"$LATEST","description":"","bot-template":"bot-import","commands-help":[],"region":"eu-west-1"}],
    'aws_cognito_identity_pool_id': 'eu-west-1:b763048b-dec0-4e71-bf1d-d18e38ba7223',
    'aws_cognito_region': 'eu-west-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'test-hosting-mobilehub-281568956',
    'aws_content_delivery_bucket_region': 'eu-west-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'dnpak9vjf529m.cloudfront.net',
    'aws_mobile_analytics_app_id': 'e3768511993844bea1a4613d1937bbc4',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'e5472131-4479-40ac-8bb3-96cec2066e4d',
    'aws_project_name': 'Test',
    'aws_project_region': 'eu-west-1',
    'aws_resource_name_prefix': 'test-mobilehub-281568956',
}

export default awsmobile;
